import React, { useState ,useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getAllProducts } from '../services/products';
import { Grid } from '@mui/material' 

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [productState, setProductState] = useState({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      const response = await getAllProducts();
      setProductState(response?.products)
      setLoading(false);
    }
    fetchData();
  }, []);


  if(loading){
    return <div className='text-center'>Loading ...</div>
  }


  return (
    <>
      <Head>
        <title>Crimeson</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='p-2 bg-teal-200'>
            <div className='text-center text-2xl mb-6'><span className='underline decoration-solid'>Knowledge</span> Base</div>
            <Grid container spacing={2}>
            {
              productState && productState.length > 0 && productState.map((singleItem)=>(
              <Grid xs={12} md={4} lg={4} xl={4} item key={singleItem.id}>
                <div className='h-full' key={singleItem.id}>
                  <div className='h-full hover:shadow-lg cursor-pointer flex flex-col bg-white rounded-b-lg'>
                    <img className='w-full h-48' src={singleItem.thumbnail} alt={singleItem.title} />
                    <div className='p-4'><div className='font-semibold hover:text-blue-600'>{singleItem.title}</div>
                    <div className='break-words text-slate-400'>{singleItem.description}</div>
                    </div>
                  </div>
                </div>
                </Grid>
              ))
            }
          </Grid>
        </div>
      </main>
    </>
  )
}
